name: BatikApp
description: A new Flutter project.

publish_to: 'none'

# Versi aplikasi, gunakan format <major>.<minor>.<patch>
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:  # Menghilangkan huruf "d" ekstra di sini
  flutter:
    sdk: flutter
  provider: ^6.0.0  # Pastikan Anda menggunakan versi yang sesuai

  # Uncomment jika Anda ingin menggunakan Google Fonts
  # google_fonts: ^5.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Versi terbaru dari flutter_lints

# Pengaturan Flutter
flutter:
  assets:
    - assets/images/blouse.jpg
    - assets/images/dress.jpg
    - assets/images/scarf.jpg
    - assets/images/bag.jpeg
    - assets/images/motif ceplok.jpg
    - assets/images/motif kawung.jpg
    - assets/images/motif mega mendung.jpg
    - assets/images/motif parang.jpg
    - assets/images/motif sido mukti.jpg
    - assets/images/home.png
    - assets/images/keranjang.png
    - assets/images/akun.png
    - assets/images/share.png
    - assets/images/panah.png
    - assets/images/star_full.png
    - assets/images/love.png
    - assets/images/back.png
    - assets/images/search.png
    - assets/images/kanan.png
